apiVersion: v1
kind: Pod
metadata:
  labels:
    app: webserver-docker
  name: webserver-docker
  namespace: default
spec:
  containers:
  - image: harbor.site-a.vcf.lab/library/webserver-docker:v4
    imagePullPolicy: Always
    name: webserver-docker
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-ntqcz
      readOnly: true
  volumes:
  - name: kube-api-access-ntqcz
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
